import * as React from "react";
import {
  Cover,
  Chapter,
  Statement,
  Split,
  Stats,
  List,
  Compare,
  Quote,
  Dense,
  Chart,
  Diagram,
  Pie,
  VerticalTimeline,
  Cycle,
  Pyramid,
  End,
  ImageFull,
  ImageLeft,
  ImageRight,
} from "./slides";

export const FIXTURES: Record<string, React.ReactElement> = {
  Cover: <Cover />,
  Chapter: <Chapter />,
  Statement: <Statement />,
  Split: <Split />,
  Stats: <Stats />,
  List: <List />,
  Compare: <Compare />,
  Quote: <Quote />,
  Dense: <Dense />,
  Chart: <Chart />,
  Diagram: <Diagram />,
  Pie: <Pie />,
  VerticalTimeline: <VerticalTimeline />,
  Cycle: <Cycle />,
  Pyramid: <Pyramid />,
  End: <End />,
  ImageFull: <ImageFull />,
  ImageLeft: <ImageLeft />,
  ImageRight: <ImageRight />,
};
