import * as React from "react";
import {
  Cover,
  Chapter,
  Statement,
  Split,
  ImageFull,
  ImageLeft,
  ImageRight,
  DiagramFull,
  DiagramLeft,
  DiagramRight,
  Stats,
  FadeList,
  List,
  Quote,
  Compare,
  Chart,
  Diagram,
  Pie,
  Pyramid,
  VerticalTimeline,
  Cycle,
  End,
} from "./slides";

export const FIXTURES: Record<string, React.ReactElement> = {
  Cover: <Cover />,
  Chapter: <Chapter />,
  Statement: <Statement />,
  Split: <Split />,
  ImageFull: <ImageFull />,
  ImageLeft: <ImageLeft />,
  ImageRight: <ImageRight />,
  DiagramFull: <DiagramFull />,
  DiagramLeft: <DiagramLeft />,
  DiagramRight: <DiagramRight />,
  Stats: <Stats />,
  FadeList: <FadeList />,
  List: <List />,
  Quote: <Quote />,
  Compare: <Compare />,
  Chart: <Chart />,
  Diagram: <Diagram />,
  Pie: <Pie />,
  Pyramid: <Pyramid />,
  VerticalTimeline: <VerticalTimeline />,
  Cycle: <Cycle />,
  End: <End />,
};
